# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ReleaseFoundry < Formula
  desc "GitHub PR-based release notes generator. Collects merged pull requests, filters by label, and renders structured release notes in multiple formats."
  homepage "https://github.com/bluefunda/release-foundry"
  version "1.8.3"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/bluefunda/release-foundry/releases/download/v1.8.3/release-foundry_1.8.3_macOS_amd64.tar.gz"
      sha256 "234c63633b4484a1b30a4218e81ed222e3784d73eb1e58b6f6001e61eb571dc8"

      define_method(:install) do
        bin.install "release-foundry"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/bluefunda/release-foundry/releases/download/v1.8.3/release-foundry_1.8.3_macOS_arm64.tar.gz"
      sha256 "4e426cb29617d1c727af6666ab32822f5b9a2b51fb77778f28f44fda131a1c38"

      define_method(:install) do
        bin.install "release-foundry"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/bluefunda/release-foundry/releases/download/v1.8.3/release-foundry_1.8.3_linux_amd64.tar.gz"
      sha256 "7c53b59ba1ce0233d349970facefe19375dc06e3a60a9ac3460a719a3c294a76"
      define_method(:install) do
        bin.install "release-foundry"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/bluefunda/release-foundry/releases/download/v1.8.3/release-foundry_1.8.3_linux_arm64.tar.gz"
      sha256 "82a66f14bb18dba94891d36d7a8d1b6216e0bf66631af653ae1673b5da9c8628"
      define_method(:install) do
        bin.install "release-foundry"
      end
    end
  end

  test do
    system "#{bin}/release-foundry", "version"
  end
end
