# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ReleaseFoundry < Formula
  desc "GitHub PR-based release notes generator. Collects merged pull requests, filters by label, and renders structured release notes in multiple formats."
  homepage "https://github.com/bluefunda/release-foundry"
  version "1.6.7"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/bluefunda/release-foundry/releases/download/v1.6.7/release-foundry_1.6.7_macOS_amd64.tar.gz"
      sha256 "8c59f09a2fa2b8de87ce98301a2b4649d44439a24cb8e7beaf720d8200e91578"

      define_method(:install) do
        bin.install "release-foundry"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/bluefunda/release-foundry/releases/download/v1.6.7/release-foundry_1.6.7_macOS_arm64.tar.gz"
      sha256 "7552dd0f0f40788927c8dd74d92a2a440eb9c9b869b93265f92a5732ff65a66b"

      define_method(:install) do
        bin.install "release-foundry"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/bluefunda/release-foundry/releases/download/v1.6.7/release-foundry_1.6.7_linux_amd64.tar.gz"
      sha256 "76f19fa763c55a5c55d5f6c1fbaad50e94a7d869e82ede5d88e28d9929e86eed"
      define_method(:install) do
        bin.install "release-foundry"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/bluefunda/release-foundry/releases/download/v1.6.7/release-foundry_1.6.7_linux_arm64.tar.gz"
      sha256 "8e0e0147d516f22280de404975e0d8f60b92e916b385bc19fe9af004d01fc4e9"
      define_method(:install) do
        bin.install "release-foundry"
      end
    end
  end

  test do
    system "#{bin}/release-foundry", "version"
  end
end
