# This file was generated by GoReleaser. DO NOT EDIT.
cask "abaper" do
  version "1.11.0"

  on_macos do
    on_intel do
      sha256 "9112f0a5b05f9e45636f04ed1d4fad386000130d397d82b43800870130e02db3"
      url "https://github.com/bluefunda/abaper/releases/download/v#{version}/abaper_#{version}_darwin_amd64.zip"
    end
    on_arm do
      sha256 "56ecb6138143de5b3b4fbe2b036657a815dff49fe4748fd4a2c4a561508ba5b9"
      url "https://github.com/bluefunda/abaper/releases/download/v#{version}/abaper_#{version}_darwin_arm64.zip"
    end
  end

  on_linux do
    on_intel do
      sha256 "1e59f05d8bd6c37b70babe5df92783a445f447b6c59f0aead5fb7349a2675669"
      url "https://github.com/bluefunda/abaper/releases/download/v#{version}/abaper_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "59e324565ec653d1c2600b3f5479277facad4d72a62ec932210d57afc0efac94"
      url "https://github.com/bluefunda/abaper/releases/download/v#{version}/abaper_#{version}_linux_arm64.tar.gz"
    end
  end

  name "abaper"
  desc "CLI for the ABAPer platform — ABAP development and deployment tooling"
  homepage "https://github.com/bluefunda/abaper"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "abaper"

  # No zap stanza required

end
