# This file was generated by GoReleaser. DO NOT EDIT.
cask "abaper" do
  version "1.16.1"

  on_macos do
    on_intel do
      sha256 "4ed99a6f43ded33bf0cc98f45872eb2da840c15fa807b245db22e0b6e5803046"
      url "https://github.com/bluefunda/abaper/releases/download/v#{version}/abaper_#{version}_darwin_amd64.zip"
    end
    on_arm do
      sha256 "43b1b5f946fc07592d861508b2592a11fa958fec039481e51540f2004079723b"
      url "https://github.com/bluefunda/abaper/releases/download/v#{version}/abaper_#{version}_darwin_arm64.zip"
    end
  end

  on_linux do
    on_intel do
      sha256 "647280c20767a6f9ded9769a27b8112fd6584462dc11577f4d2873a64a4b9ad2"
      url "https://github.com/bluefunda/abaper/releases/download/v#{version}/abaper_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "22bf5b6450f4bfa9d0c1e3faff383dfc828105b7015cb1813cc54e9928e51254"
      url "https://github.com/bluefunda/abaper/releases/download/v#{version}/abaper_#{version}_linux_arm64.tar.gz"
    end
  end

  name "abaper"
  desc "CLI for the ABAPer platform — ABAP development and deployment tooling"
  homepage "https://github.com/bluefunda/abaper"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "abaper"

  # No zap stanza required

end
