# This file was generated by GoReleaser. DO NOT EDIT.
cask "abaper" do
  version "1.7.0"

  on_macos do
    on_intel do
      sha256 "f265c8b1638feb4e9a7d2ff0105272486753d50036578a367ce60051a9bef9dd"
      url "https://github.com/bluefunda/abaper/releases/download/v#{version}/abaper_#{version}_darwin_amd64.zip"
    end
    on_arm do
      sha256 "deda2937fce267d7f23ee2c5753009fc1295d45e750e8739f0cdd0e16f8470ab"
      url "https://github.com/bluefunda/abaper/releases/download/v#{version}/abaper_#{version}_darwin_arm64.zip"
    end
  end

  on_linux do
    on_intel do
      sha256 "5f09e3d40a180c434546697527eebba6f3ab6a2292322d0fec49cf77bee8c91d"
      url "https://github.com/bluefunda/abaper/releases/download/v#{version}/abaper_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "0e299cdd64eef241656e98473a5567b05e1d28287f3653d82aa9ec665bdedd0a"
      url "https://github.com/bluefunda/abaper/releases/download/v#{version}/abaper_#{version}_linux_arm64.tar.gz"
    end
  end

  name "abaper"
  desc "CLI for the ABAPer platform — ABAP development and deployment tooling"
  homepage "https://github.com/bluefunda/abaper"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "abaper"

  # No zap stanza required

end
