# This file was generated by GoReleaser. DO NOT EDIT.
cask "ai" do
  version "1.3.1"

  on_macos do
    on_intel do
      sha256 "29a952bdb08974825b6164c0414ceeb5ce5b41b4ffd1924b6da899e2d473577c"
      url "https://github.com/bluefunda/cai-cli/releases/download/v#{version}/ai_#{version}_darwin_amd64.zip"
    end
    on_arm do
      sha256 "0bc4a02db5f0a9edbd0ec09446cde9cc7d4c25e2b55c17a9af7e6716560cf187"
      url "https://github.com/bluefunda/cai-cli/releases/download/v#{version}/ai_#{version}_darwin_arm64.zip"
    end
  end

  on_linux do
    on_intel do
      sha256 "a15d4602136f613d188b384281d6904fd9aea60c09bec5647cba9e17836e4d62"
      url "https://github.com/bluefunda/cai-cli/releases/download/v#{version}/ai_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "4463bd26f2b933e8eea17e687e78aa86bedd932ae0064949c194d3956bace6b9"
      url "https://github.com/bluefunda/cai-cli/releases/download/v#{version}/ai_#{version}_linux_arm64.tar.gz"
    end
  end

  name "ai"
  desc "CLI for BlueFunda AI — context-aware AI agents for SAP operations"
  homepage "https://github.com/bluefunda/cai-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ai"

  # No zap stanza required

end
