# This file was generated by GoReleaser. DO NOT EDIT.
cask "bai" do
  version "1.9.0"

  on_macos do
    on_intel do
      sha256 "a54756517cca24f9002f795cbdc9ccc92113a2f05bd43431591ededa98391e3f"
      url "https://github.com/bluefunda/bluefunda-ai/releases/download/v#{version}/bai_#{version}_darwin_amd64.zip"
    end
    on_arm do
      sha256 "459cb874d91691305661a9448e9d829cd07a0566d22fc30d3e5bbc3e7e15692f"
      url "https://github.com/bluefunda/bluefunda-ai/releases/download/v#{version}/bai_#{version}_darwin_arm64.zip"
    end
  end

  on_linux do
    on_intel do
      sha256 "aa3871a6e98ab1aff6393269ec34415e802eee8f0e06842c262bd41a87b40ca7"
      url "https://github.com/bluefunda/bluefunda-ai/releases/download/v#{version}/bai_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "ecdc1c3074eb119f9a6092a10a42c4c1085d427c4364f32e291984dce6f16775"
      url "https://github.com/bluefunda/bluefunda-ai/releases/download/v#{version}/bai_#{version}_linux_arm64.tar.gz"
    end
  end

  name "bai"
  desc "CLI for BlueFunda AI — context-aware AI agents for SAP operations"
  homepage "https://github.com/bluefunda/bluefunda-ai"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "bai"

  # No zap stanza required

end
