# This file was generated by GoReleaser. DO NOT EDIT.
cask "bai" do
  version "1.12.0"

  on_macos do
    on_intel do
      sha256 "f50dd578356bab6e34f7ceb6dd8ca3ee592ffa45015e768c2dd65b205762e87a"
      url "https://github.com/bluefunda/bluefunda-ai/releases/download/v#{version}/bai_#{version}_darwin_amd64.zip"
    end
    on_arm do
      sha256 "aa59610c386bac61b33e780f8742352aeffbc3c83e57a1280b6da5acfe3f14f6"
      url "https://github.com/bluefunda/bluefunda-ai/releases/download/v#{version}/bai_#{version}_darwin_arm64.zip"
    end
  end

  on_linux do
    on_intel do
      sha256 "f14670b005a49a609a084ae7ada88eadca5a610bc85175ac5d40a78056f12684"
      url "https://github.com/bluefunda/bluefunda-ai/releases/download/v#{version}/bai_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "0fa7d11ece23b9ec2f584477347d68b68927acc414c85a3bdf5c6c97f6be4ed9"
      url "https://github.com/bluefunda/bluefunda-ai/releases/download/v#{version}/bai_#{version}_linux_arm64.tar.gz"
    end
  end

  name "bai"
  desc "CLI for BlueFunda AI — context-aware AI agents for SAP operations"
  homepage "https://github.com/bluefunda/bluefunda-ai"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "bai"

  # No zap stanza required

end
