# This file was generated by GoReleaser. DO NOT EDIT.
cask "bai" do
  version "1.13.0"

  on_macos do
    on_intel do
      sha256 "8eb6f1c2e0d5731948fb8891918da79fa79e2c6231e6caff0c68065912d956b6"
      url "https://github.com/bluefunda/bluefunda-ai/releases/download/v#{version}/bai_#{version}_darwin_amd64.zip"
    end
    on_arm do
      sha256 "95e723a524404c282c895fa2dc3853d3755e6467a083538a90af2f06f290f4f8"
      url "https://github.com/bluefunda/bluefunda-ai/releases/download/v#{version}/bai_#{version}_darwin_arm64.zip"
    end
  end

  on_linux do
    on_intel do
      sha256 "f4ec26d1c09436e69c4ece73380632850c9e358c88c89e8fe3e0a641aad5f923"
      url "https://github.com/bluefunda/bluefunda-ai/releases/download/v#{version}/bai_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "a162aaa1af574a6c30ea3bfd64cfc15429576ae8ac29dee6939d41f3cbafbbf3"
      url "https://github.com/bluefunda/bluefunda-ai/releases/download/v#{version}/bai_#{version}_linux_arm64.tar.gz"
    end
  end

  name "bai"
  desc "CLI for BlueFunda AI — context-aware AI agents for SAP operations"
  homepage "https://github.com/bluefunda/bluefunda-ai"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "bai"

  # No zap stanza required

end
