# This file was generated by GoReleaser. DO NOT EDIT.
cask "breq" do
  version "1.7.0"

  on_macos do
    on_intel do
      sha256 "e04b311fefb47740c223363e8bd7a91931315c0f7144d808e8a0d241ac9af73f"
      url "https://github.com/bluefunda/bluerequests/releases/download/v#{version}/breq_#{version}_darwin_amd64.zip"
    end
    on_arm do
      sha256 "502638d82ca2accad0017eec74ccc8a8e2d34519b170ec38225df8c6a3123642"
      url "https://github.com/bluefunda/bluerequests/releases/download/v#{version}/breq_#{version}_darwin_arm64.zip"
    end
  end

  on_linux do
    on_intel do
      sha256 "0739823a83657aa5ad96a92dd7b59154666ba2b1cf58d9cd8187a759fef472ac"
      url "https://github.com/bluefunda/bluerequests/releases/download/v#{version}/breq_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "1865c3e4c3b5f57809f715ca0d910e29acbea0764d31d868ff059df11475dae9"
      url "https://github.com/bluefunda/bluerequests/releases/download/v#{version}/breq_#{version}_linux_arm64.tar.gz"
    end
  end

  name "breq"
  desc "CLI for the BlueRequests change and release management platform"
  homepage "https://github.com/bluefunda/bluerequests"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "breq"

  # No zap stanza required

end
