# This file was generated by GoReleaser. DO NOT EDIT.
cask "breq" do
  version "1.8.0"

  on_macos do
    on_intel do
      sha256 "c4ea02943fb835b9a7a570d8ca0b28cc9af2f6ec636a874aa3b3a6d79486b3f5"
      url "https://github.com/bluefunda/bluerequests/releases/download/v#{version}/breq_#{version}_darwin_amd64.zip"
    end
    on_arm do
      sha256 "3b01b00716c18aafc6d988cd81e34b39b55cc969fc63333bdd0a183577a22582"
      url "https://github.com/bluefunda/bluerequests/releases/download/v#{version}/breq_#{version}_darwin_arm64.zip"
    end
  end

  on_linux do
    on_intel do
      sha256 "2ab69d2fe917fdce44e3522f63b3845712efa207962fda4a5716f7d9d78f42b6"
      url "https://github.com/bluefunda/bluerequests/releases/download/v#{version}/breq_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "b1f50feb0842addc1f992ae463e9ebf1f8955e239a9f5c80717094c9ac1b0dc3"
      url "https://github.com/bluefunda/bluerequests/releases/download/v#{version}/breq_#{version}_linux_arm64.tar.gz"
    end
  end

  name "breq"
  desc "CLI for the bluerequests change and release management platform"
  homepage "https://github.com/bluefunda/bluerequests"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "breq"

  # No zap stanza required

end
