# This file was generated by GoReleaser. DO NOT EDIT.
cask "breq" do
  version "1.7.1"

  on_macos do
    on_intel do
      sha256 "010577b89dfad8962a4ce19b9f3a3dbb44523c014695b2ce4c1574ddacf04fdf"
      url "https://github.com/bluefunda/bluerequests/releases/download/v#{version}/breq_#{version}_darwin_amd64.zip"
    end
    on_arm do
      sha256 "66373c20afb9993d8cd42d13df60c2f1b79998772a1b8f26a276f380f2f1f073"
      url "https://github.com/bluefunda/bluerequests/releases/download/v#{version}/breq_#{version}_darwin_arm64.zip"
    end
  end

  on_linux do
    on_intel do
      sha256 "c8d27f0914ffb93f55b2774d1d28eef28001f0615677384f146ec143fe731290"
      url "https://github.com/bluefunda/bluerequests/releases/download/v#{version}/breq_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "c56cf0cfd36ad91a1711f4d06100c820d76788437d442cc7260d6448076e1196"
      url "https://github.com/bluefunda/bluerequests/releases/download/v#{version}/breq_#{version}_linux_arm64.tar.gz"
    end
  end

  name "breq"
  desc "CLI for the bluerequests change and release management platform"
  homepage "https://github.com/bluefunda/bluerequests"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "breq"

  # No zap stanza required

end
