# This file was generated by GoReleaser. DO NOT EDIT.
cask "requests" do
  version "1.3.0"

  on_macos do
    on_intel do
      sha256 "a6b895eb988297ce6e48a01735f9bfe5bca691e769dbe1c1b5747d1a6855ef47"
      url "https://github.com/bluefunda/trm-cli/releases/download/v#{version}/requests_#{version}_darwin_amd64.zip"
    end
    on_arm do
      sha256 "35018e153df7ba70f8e4141d469d269f95294cdc8dd882d6bf06bb384e2abd45"
      url "https://github.com/bluefunda/trm-cli/releases/download/v#{version}/requests_#{version}_darwin_arm64.zip"
    end
  end

  on_linux do
    on_intel do
      sha256 "06a62b34cb97a5c6555c5602743f6c8dd88214e76de194f7edcc7be6c9604344"
      url "https://github.com/bluefunda/trm-cli/releases/download/v#{version}/requests_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "74bf06b68940122ab72b30893bb5510dfaab707c77e0fed10e3015edf9f05fff"
      url "https://github.com/bluefunda/trm-cli/releases/download/v#{version}/requests_#{version}_linux_arm64.tar.gz"
    end
  end

  name "requests"
  desc "CLI for the bluerequests change/release management platform."
  homepage "https://github.com/bluefunda/trm-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "requests"

  # No zap stanza required

end
