# This file was generated by GoReleaser. DO NOT EDIT.
cask "requests" do
  version "1.4.0"

  on_macos do
    on_intel do
      sha256 "c49ac3f21d8985138d6be2872e161719817f970ac31eaf69ff59ba3c01b1e8ec"
      url "https://github.com/bluefunda/trm-cli/releases/download/v#{version}/requests_#{version}_darwin_amd64.zip"
    end
    on_arm do
      sha256 "379bd4ff77ef512e094b9396367d5bfe69a21614ab9fc120ccede497765bec46"
      url "https://github.com/bluefunda/trm-cli/releases/download/v#{version}/requests_#{version}_darwin_arm64.zip"
    end
  end

  on_linux do
    on_intel do
      sha256 "1a101e527140f143d078a22517c6176c63e1fc6ba015aa6bd5ababb6a59879bd"
      url "https://github.com/bluefunda/trm-cli/releases/download/v#{version}/requests_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "cafc0e82fb77791731bc21f2ba9bbcb51f595c114f9f7eede42e696d01376379"
      url "https://github.com/bluefunda/trm-cli/releases/download/v#{version}/requests_#{version}_linux_arm64.tar.gz"
    end
  end

  name "requests"
  desc "CLI for the bluerequests change/release management platform."
  homepage "https://github.com/bluefunda/trm-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "requests"

  # No zap stanza required

end
