# This file was generated by GoReleaser. DO NOT EDIT.
cask "requests" do
  version "1.2.1"

  on_macos do
    on_intel do
      sha256 "54f18974c0ea0cfbad2796f45f138fb317079eedfeb25a91a8f2e03fe283b4f6"
      url "https://github.com/bluefunda/trm-cli/releases/download/v#{version}/requests_#{version}_darwin_amd64.zip"
    end
    on_arm do
      sha256 "bf2d41a4282583fcd3480daacd2c1453e26c4d89e1e33893994ad8910a5a226d"
      url "https://github.com/bluefunda/trm-cli/releases/download/v#{version}/requests_#{version}_darwin_arm64.zip"
    end
  end

  on_linux do
    on_intel do
      sha256 "007f78a431a508e92f0f352334b1cbfabf396862b43fdf81cfd7f8d18d0c37bc"
      url "https://github.com/bluefunda/trm-cli/releases/download/v#{version}/requests_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "c7a2ce07e9a91e5805a80dd0fd1df73ba4cc92a0804ecdd0de10e097331ed1d0"
      url "https://github.com/bluefunda/trm-cli/releases/download/v#{version}/requests_#{version}_linux_arm64.tar.gz"
    end
  end

  name "requests"
  desc "CLI for the bluerequests change/release management platform."
  homepage "https://github.com/bluefunda/trm-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "requests"

  # No zap stanza required

end
