# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Abaper < Formula
  desc "Command line interface for the ABAPer platform"
  homepage "https://abaper.bluefunda.com"
  version "1.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/bluefunda/abaper-cli/releases/download/v1.1.0/abaper_1.1.0_darwin_amd64.tar.gz"
      sha256 "3a2d63ff1688386ff672f8aa45630dfefd70ac04b7cb0631934bf944c46a2db4"

      define_method(:install) do
        bin.install "abaper"
        man1.install "man/abaper.1"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/bluefunda/abaper-cli/releases/download/v1.1.0/abaper_1.1.0_darwin_arm64.tar.gz"
      sha256 "281bb2ff2214f0bf2e3341e7a7ccbe9a4344e0cf250e9124c9d13fb119c47ef1"

      define_method(:install) do
        bin.install "abaper"
        man1.install "man/abaper.1"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/bluefunda/abaper-cli/releases/download/v1.1.0/abaper_1.1.0_linux_amd64.tar.gz"
      sha256 "2a70d852a9b3819d6398185ad42d3ea4dd8bbf45a9dc4cc87f887e06e10c77ec"
      define_method(:install) do
        bin.install "abaper"
        man1.install "man/abaper.1"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/bluefunda/abaper-cli/releases/download/v1.1.0/abaper_1.1.0_linux_arm64.tar.gz"
      sha256 "ae01d529aedd6136484c79788772a1ab9f766a356eb1382cc5834a791c3bfdc2"
      define_method(:install) do
        bin.install "abaper"
        man1.install "man/abaper.1"
      end
    end
  end

  test do
    system "#{bin}/abaper", "version"
  end
end
