# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ai < Formula
  desc "CLI for BlueFunda AI — context-aware AI agents for SAP operations"
  homepage "https://github.com/bluefunda/cai-cli"
  version "1.2.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/bluefunda/cai-cli/releases/download/v1.2.3/ai_1.2.3_darwin_amd64.zip"
      sha256 "de3b3397db7641d61f222fc4b49d96f391a5d229bd74182bf5f377f3736f62fe"

      define_method(:install) do
        bin.install "ai"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/bluefunda/cai-cli/releases/download/v1.2.3/ai_1.2.3_darwin_arm64.zip"
      sha256 "271621458e87fc7a1becc4f4b8bf1967ac73d656972bc2be535770626d4d25b0"

      define_method(:install) do
        bin.install "ai"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/bluefunda/cai-cli/releases/download/v1.2.3/ai_1.2.3_linux_amd64.tar.gz"
      sha256 "c85e929115c8d8dfcd5e5a37b55e168bc6d4368ac30b25ac12e487571040dc40"

      define_method(:install) do
        bin.install "ai"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/bluefunda/cai-cli/releases/download/v1.2.3/ai_1.2.3_linux_arm64.tar.gz"
      sha256 "723d2661b7e8dc2ad2dde5051de70ce5d1391e83b49f9dec145164019af3bd7c"

      define_method(:install) do
        bin.install "ai"
      end
    end
  end

  test do
    system "#{bin}/ai", "version"
  end
end
