# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bai < Formula
  desc "CLI for BlueFunda AI — context-aware AI agents for SAP operations"
  homepage "https://github.com/bluefunda/bluefunda-ai"
  version "1.33.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/bluefunda/bluefunda-ai/releases/download/v1.33.1/bai_1.33.1_darwin_amd64.zip"
      sha256 "e9d132e04691f11b09bcf57ad51ddd330f878900fe45e5d44e3a0d20b83f1773"

      define_method(:install) do
        bin.install "bai"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/bluefunda/bluefunda-ai/releases/download/v1.33.1/bai_1.33.1_darwin_arm64.zip"
      sha256 "05d3d334db3ff1349d5b0924d19debd4d2c9cbf0eb509c39f6d19bd014670903"

      define_method(:install) do
        bin.install "bai"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/bluefunda/bluefunda-ai/releases/download/v1.33.1/bai_1.33.1_linux_amd64.tar.gz"
      sha256 "e70dd642c4f9eae3e39f10677fab279e44522a48a63ed8d5acbe0869b1cbcfab"
      define_method(:install) do
        bin.install "bai"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/bluefunda/bluefunda-ai/releases/download/v1.33.1/bai_1.33.1_linux_arm64.tar.gz"
      sha256 "8f4a7410525d535207dcb25493f28d84a2a2b8ebbef6262c2dc02a1e97c2affe"
      define_method(:install) do
        bin.install "bai"
      end
    end
  end
end
